# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
steps:

- task: DownloadSecureFile@1
  inputs:
    secureFile: '.env'

# Copy files
# Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
- task: CopyFiles@2
  inputs:
    #sourceFolder: # Optional
    contents: '**'
    targetFolder: . 
    #cleanTargetFolder: false # Optional
    overWrite: false # Optional
    #flattenFolders: false # Optional
    #preserveTimestamp: false # Optional
    retryCount: 1 # Optional
    #ignoreMakeDirErrors: false # Optional

- task: DockerCompose@0
  displayName: Combine configuration
  inputs:
    action: Combine configuration
    dockerComposeFile: docker-compose.yml
    additionalDockerComposeFiles: docker-compose.override.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    outputDockerComposeFile: $(Build.StagingDirectory)/docker-compose.yml