# # Starter pipeline

trigger:
- master



# variables:
#   azureSubscription: xyz devops
#   azureContainerRegistryEndPoint: testfastapi.azurecr.io


# Agent should be non micorosft
pool:
  vmImageName: ubuntu-latest

steps:

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'secureFile'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: secureFile
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: DockerCompose@0
  displayName: Build services
  inputs:
    action: Build services
    azureSubscription: 'Visual Studio Professional Subscription(a2d66221-cfb0-4024-b856-b74e60ffbaa8)'
    azureContainerRegistry: '{"loginServer":"testfastapi.azurecr.io", "id" : "/subscriptions/a2d66221-cfb0-4024-b856-b74e60ffbaa8/resourceGroups/Test-fastAPI/providers/Microsoft.ContainerRegistry/registries/TestFastAPI"}'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: '**/docker-compose.override.yml'
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildId)