# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Running up!
  displayName: 'Pipeline started'

- script: |
    docker-compose -f .\docker-compose.yml -f .\docker-compose.override.yml up --build  --remove-orphans
    
  displayName: 'Deploying App'

