default_context:
  project_name: 'porfolio'
  project_slug: 'porfolio'
  domain_main: 'hernan.io'
  domain_staging: 'dev.hernan.io'
  docker_swarm_stack_name_main: 'hernan-io'
  docker_swarm_stack_name_staging: 'dev-hernan-io'
  secret_key: '0091a006b40e554ab17a5b5a3ce31ff12baf944484ac56de8582b0b172fd65bb'
  first_superuser: 'admin@hernan.io'
  first_superuser_password: 'Mate1822'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.hernan.io", "https://dev.hernan.io", "https://hernan.io", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@hernan.io'
  postgres_password: 'Mate@1822'
  pgadmin_default_user: 'admin@hernan.io'
  pgadmin_default_user_password: 'Mate1822'
  traefik_constraint_tag: 'hernan.io'
  traefik_constraint_tag_staging: 'dev.hernan.io'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Mate1822'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
